#@see java.time.Duration.parse(CharSequence)
#relevancy-engine.model.embedding.remote.base-url=http://localhost:11434/api/embed
#relevancy-engine.model.embedding.remote.model-name=nomic-embed-text
relevancy-engine.model.embedding.remote.timeout=PT2M
relevancy-engine.model.tokenizer.remote.estimate-cache-size=2500
relevancy-engine.model.tokenizer.remote.estimate-cache-expire=20000
relevancy-engine.model.embedding.remote.parallelism=65